spring.application.name=BootMVCProj04-Project-CRUDOperations


#Data source comfigurations
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#embeded server
server.port=4041

#jpa-hibernet properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#view resolver configurations
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
